sonar.projectKey=SPA-L01_SPA.Frontend
sonar.organization=spa-l01
sonar.sources=app,components
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
# Loại bỏ triệt để các thư mục rác
sonar.exclusions=node_modules/**, dist/**, .expo/**, assets/**, scripts/**, *.config.js, package-lock.json
sonar.cpd.exclusions=__tests__/**
