sonar.projectKey=spa-parking-mobile
sonar.organization=your-org
sonar.sources=app,components
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.exclusions=node_modules/**, dist/**, .expo/**
